### PR TITLE
Fixed std/path module import error

### PR DESCRIPTION
**Pull request by gjuoun**
Fix error: Failed to get compiled source code of ../denjucks/src/deps/path/std/path/mod.ts.

### CODE REVIEW

**Comment by cj81499** [comment]
@denjucks can this be reviewed (& merged) asap? The module is currently unusable.

**Comment by denjucks** [comment]
Apologies on the delayed response. Some of this should be fixed from this pull request: [https://github.com/denjucks/denjucks/pull/12](https://github.com/denjucks/denjucks/pull/12). However, I am not understanding what causing this error. I am getting `error: Failed to get compiled source code of https://deno.land/std@0.59.0/path/mod.ts.` after the pull requests when using the type declaration file, but works fine without it. Any ideas?

**Comment by gjuoun** [comment]
#12 is a similar pull request like this. I'm closing it now

**Comment by cj81499** [comment]
@denjucks See [here](https://github.com/denoland/deno/issues/6363). You might just need to refresh Deno's cache. I had the same issue.

**Comment by Whobeu** [comment]
I am relatively new to Deno and came across this issue searching for "Failed to get compiled source code of ". I am running 1.1.2 and for me the "cache" option does not solve the problem:

```
C:\>deno run gpn.ts
error: Failed to get compiled source code of file:///C:/Users/Robert%20G.%20Schaffrath/Node/LIGP/deno/src/lib.deno_runtime.d.ts.
Reason: The system cannot find the file specified. (os error 2)

C:\>deno cache file:///C:/Users/Robert%20G.%20Schaffrath/Node/LIGP/deno/src/lib.deno_runtime.d.ts
Check file:///C:/Users/Robert%20G.%20Schaffrath/Node/LIGP/deno/src/lib.deno_runtime.d.ts
error: Failed to get compiled source code of file:///C:/Users/Robert%20G.%20Schaffrath/Node/LIGP/deno/src/lib.deno_runtime.d.ts.
Reason: The system cannot find the file specified. (os error 2)

C:\>dir lib.deno_runtime.d.ts
Directory of C:\Users\Robert G. Schaffrath\Node\LIGP\deno\src

06/30/2020  11:14 AM           120,310 lib.deno_runtime.d.ts
```
The same problem if I use an external resource:

```
C:\>deno run gpn.ts
Check file:///C:/Users/Robert%20G.%20Schaffrath/Node/LIGP/deno/src/gpn.ts
error: Failed to get compiled source code of https://cdn.jsdelivr.net/npm/typescript@3.9.5/lib/lib.es2019.full.d.ts.
Reason: The system cannot find the file specified. (os error 2)

C:\>deno cache https://cdn.jsdelivr.net/npm/typescript@3.9.5/lib/lib.es2019.full.d.ts
Check https://cdn.jsdelivr.net/npm/typescript@3.9.5/lib/lib.es2019.full.d.ts
error: Failed to get compiled source code of https://cdn.jsdelivr.net/npm/typescript@3.9.5/lib/lib.es2019.full.d.ts.
Reason: The system cannot find the file specified. (os error 2)

**Comment by cj81499** [comment]
@Whobeu try to cache `gpn.ts`.

**Comment by Whobeu** [comment]
Same error on both local module and changing to external module:

```
C:\>deno cache gpn.ts
Check file:///C:/Users/Robert%20G.%20Schaffrath/Node/LIGP/deno/src/gpn.ts
error: Failed to get compiled source code of file:///C:/Users/Robert%20G.%20Schaffrath/Node/LIGP/deno/src/lib.deno_runtime.d.ts.
Reason: The system cannot find the file specified. (os error 2)
```

```
C:\>deno cache gpn.ts
Check file:///C:/Users/Robert%20G.%20Schaffrath/Node/LIGP/deno/src/gpn.ts
error: Failed to get compiled source code of https://cdn.jsdelivr.net/npm/typescript@3.9.5/lib/lib.es2019.full.d.ts.
Reason: The system cannot find the file specified. (os error 2)
```

I wonder if Deno is having problems with whitespaces in pathnames. Unrelated to this issue, I was going to open an issue about upgrading. I tried running the following command yesterday:

`deno upgrade --version 1.1.2`

However, it failed when it stopped parsing the path at "/Robert" of "C:/Users/Robert G. Schaffrath". I finally upgraded successfully using PowerShell.

**Comment by cj81499** [comment]
It's very possible that it's a deno problem. Any chance you could share your code so we could try to replicate?

**Comment by Whobeu** [comment]
> It's very possible that it's a deno problem. Any chance you could share your code so we could try to replicate?

Sure. It is just some simple personal stuff that has no legal entanglements and is nothing special. I can ZIP it up and deposit it somewhere or I can put it on an AWS S3 location. It is nothing really big.

**Pull request closed without merging**
